# Thanks to Stefan Stranger
# https://stefanstranger.github.io/2018/12/30/UseAzurePipelinesToPublishPowerShellModule/

trigger:
  branches:
    include:
    - master

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-template.yml # Template reference

  - task: GitHubRelease@0
    inputs:
      connection: "GHC_AZDO"
      userRepository: "timoline/PSRES"
      action: 'create'
      