# Thanks to Stefan Stranger
# https://stefanstranger.github.io/2018/12/30/UseAzurePipelinesToPublishPowerShellModule/

trigger:
  branches:
    include:
    - master

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - task: PowerShell@2
    displayName: 'Run tests'
    inputs:
      targetType: Inline
      script: ./build.ps1 -Bootstrap -Test

  - task: PublishTestResults@2
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/TestResults.xml'
    condition: succeededOrFailed()


