# Thanks to Stefan Stranger
# https://stefanstranger.github.io/2018/12/30/UseAzurePipelinesToPublishPowerShellModule/

trigger:
  branches:
    include:
    - master

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
    - task: Pester Powershell unittest@2
      inputs:
        ItemSpec: 'tests\*.tests.ps1'
        TestParams: '-OutputFormat NUnitXml -OutputFile TestResults.xml'
        FailOnError: true

    - task: PublishTestResults@2
      inputs:
        testRunner: NUnit
        testResultsFiles: '../**/TEST-*.xml'
      condition: succeededOrFailed()


