# Thanks to Stefan Stranger

# https://stefanstranger.github.io/2018/12/30/UseAzurePipelinesToPublishPowerShellModule/

 

trigger:
  branches:
    include:
    - master

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-template.yml # Template reference